# this is the correct file

FROM swipl

# RUN apt-get update

# copies all the files form 'src' directory to the current directory of the Prologues' comtainer
COPY src/* ./

MAINTAINER ravi <raviprakashravi.cf>

# build an image using --->     docker build . <Tag or Name of img>